# frozen_string_literal: true

[{ name: 'Josef Newgarden',
   nationality_iso3: 'USA',
   date_of_birth: '1990-12-22',
   team: 'Team Penske' },
 { name: 'Ricky Stenhouse Jr.',
   nationality_iso3: 'USA',
   date_of_birth: '1987-10-02',
   team: 'JTG Daugherty Racing' },
 { name: 'Sébastien Bourdais',
   nationality_iso3: 'FRA',
   date_of_birth: '1979-02-28',
   team: 'Chip Ganassi Racing' },
 { name: 'Renger van der Zande',
   nationality_iso3: 'NLD',
   date_of_birth: '1986-02-16',
   team: 'Chip Ganassi Racing' },
 { name: 'Max Verstappen',
   nationality_iso3: 'NLD',
   date_of_birth: '1997-09-30',
   team: 'Red Bull Racing' },
 { name: 'James Calado',
   nationality_iso3: 'GBR',
   date_of_birth: '1989-06-13',
   team: 'AF Corse' },
 { name: 'Antonio Giovinazzi',
   nationality_iso3: 'ITA',
   date_of_birth: '1993-12-14',
   team: 'AF Corse' },
 { name: 'Alessandro Pier Guidi',
   nationality_iso3: 'ITA',
   date_of_birth: '1983-12-18',
   team: 'AF Corse' },
 { name: 'Earl Bamber',
   nationality_iso3: 'NZL',
   date_of_birth: '1990-07-09',
   team: 'Frikadelli Racing Team' },
 { name: 'Nicky Catsburg',
   nationality_iso3: 'NLD',
   date_of_birth: '1988-02-15',
   team: 'Frikadelli Racing Team' },
 { name: 'Felipe Fernández Laser',
   nationality_iso3: 'DEU',
   date_of_birth: '1997-05-31',
   team: 'Frikadelli Racing Team' },
 { name: 'David Pittard',
   nationality_iso3: 'GBR',
   date_of_birth: '1991-10-29',
   team: 'Frikadelli Racing Team' }].each do |driver|
  driver[:team] = Team.find_by(name: driver[:team])
  Driver.create!(driver)
end
